services:
  valkey:
    image: valkey/valkey:8.0
    container_name: valkey
    ports:
      - "6379:6379"
    volumes:
      - valkey-data:/data
    command: ["valkey-server", "--appendonly", "yes"]
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant
    ports: 
      - "6333:6333"

volumes:
  valkey-data:
